### ISSUE TITLE
Complicated system, not as easy as BluescreenSimulator by FlyTechVideos

### ISSUE THREAD

**Issue by Herobrine8761** [MarkusMaal/BlueScreenSimulatorPlus#3]
The UI is very complicated. Please make it simplified so a regular non-techie guy can also operate this app of yours. Thank you

**Comment by Fatihkazim** [comment]
Bruh just try to get used to it

**Comment by Herobrine8761** [comment]
Okay then, I'll resort to BlueScreen Simulator by FlyTechVideos only.
